/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static java.time.Clock.system;
import javax.swing.JOptionPane;

/**
 *
 * @author ETECIA
 */
public class Principal extends javax.swing.JFrame {
 static int val1=0;
 static int val2=0;
 static int res=0;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        nome2 = new javax.swing.JLabel();
        nome1 = new javax.swing.JLabel();
        valor2 = new javax.swing.JTextField();
        valor1 = new javax.swing.JTextField();
        soma = new javax.swing.JButton();
        div = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        resultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lousa.jpg"))); // NOI18N
        panelImage1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CALCULADORA");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(240, 20, 320, 50);

        nome2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nome2.setForeground(new java.awt.Color(255, 255, 255));
        nome2.setText("Valor 2:");
        panelImage1.add(nome2);
        nome2.setBounds(80, 170, 110, 30);

        nome1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nome1.setForeground(new java.awt.Color(255, 255, 255));
        nome1.setText("Valor 1:");
        panelImage1.add(nome1);
        nome1.setBounds(80, 100, 110, 30);

        valor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor2ActionPerformed(evt);
            }
        });
        panelImage1.add(valor2);
        valor2.setBounds(190, 170, 110, 30);

        valor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor1ActionPerformed(evt);
            }
        });
        panelImage1.add(valor1);
        valor1.setBounds(190, 100, 110, 30);

        soma.setBackground(new java.awt.Color(0, 153, 102));
        soma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        soma.setText("+");
        soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaActionPerformed(evt);
            }
        });
        panelImage1.add(soma);
        soma.setBounds(90, 240, 80, 40);

        div.setBackground(new java.awt.Color(0, 153, 102));
        div.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        div.setText("/");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        panelImage1.add(div);
        div.setBounds(390, 240, 80, 40);

        multi.setBackground(new java.awt.Color(0, 153, 102));
        multi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        multi.setText("x");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        panelImage1.add(multi);
        multi.setBounds(290, 240, 80, 40);

        sub.setBackground(new java.awt.Color(0, 153, 102));
        sub.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sub.setText("-");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        panelImage1.add(sub);
        sub.setBounds(190, 240, 80, 40);

        sair.setBackground(new java.awt.Color(255, 0, 51));
        sair.setText("SAIR");
        sair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        panelImage1.add(sair);
        sair.setBounds(650, 30, 90, 40);

        jPanel1.setLayout(null);

        resultado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(resultado);
        resultado.setBounds(10, 10, 150, 20);

        panelImage1.add(jPanel1);
        jPanel1.setBounds(420, 140, 180, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("=");
        panelImage1.add(jLabel2);
        jLabel2.setBounds(350, 140, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void valor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor1ActionPerformed
          val1 = Integer.parseInt(valor1.getText());
    }//GEN-LAST:event_valor1ActionPerformed

    private void valor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor2ActionPerformed
          val2 = Integer.parseInt(valor2.getText());
    }//GEN-LAST:event_valor2ActionPerformed

    private void somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somaActionPerformed
       val1 = Integer.parseInt(valor1.getText());
       val2 = Integer.parseInt(valor2.getText()); 
       
        //JOptionPane.showMessageDialog(null, "O resultadado da soma é "+ (val1+val2));
    }//GEN-LAST:event_somaActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
         val1 = Integer.parseInt(valor1.getText());
         val2 = Integer.parseInt(valor2.getText()); 
        //JOptionPane.showMessageDialog(null, "O resultadado da soma é "+ (val1*val2));
    }//GEN-LAST:event_multiActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
       val1 = Integer.parseInt(valor1.getText());
       val2 = Integer.parseInt(valor2.getText()); 
        //JOptionPane.showMessageDialog(null, "O resultadado da soma é "+ (val1-val2));
    }//GEN-LAST:event_subActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        val1 = (int) Double.parseDouble(valor1.getText());
        val2 = (int) Double.parseDouble(valor2.getText()); 
        //JOptionPane.showMessageDialog(null, "O resultadado da soma é "+ (val1/val2));
    }//GEN-LAST:event_divActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton div;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multi;
    private javax.swing.JLabel nome1;
    private javax.swing.JLabel nome2;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JLabel resultado;
    private javax.swing.JButton sair;
    private javax.swing.JButton soma;
    private javax.swing.JButton sub;
    private javax.swing.JTextField valor1;
    private javax.swing.JTextField valor2;
    // End of variables declaration//GEN-END:variables
}
