/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Gerador;
import static Model.Gerador.megasena;
import static View.MegaSena.num1;
import static View.MegaSena.num2;
import static View.MegaSena.num3;
import static View.MegaSena.num4;
import static View.MegaSena.num5;
import static View.MegaSena.num6;

/**
 *
 * @author ETECIA
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        mega = new javax.swing.JButton();
        Lotomania = new javax.swing.JButton();
        Quina = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 0), 2, true));
        jPanel3.setLayout(null);

        mega.setBackground(new java.awt.Color(102, 255, 102));
        mega.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mega.setText("Mega-Sena");
        mega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                megaActionPerformed(evt);
            }
        });
        jPanel3.add(mega);
        mega.setBounds(20, 110, 190, 50);

        Lotomania.setBackground(new java.awt.Color(255, 153, 0));
        Lotomania.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lotomania.setText("LotoMania");
        jPanel3.add(Lotomania);
        Lotomania.setBounds(20, 230, 190, 50);

        Quina.setBackground(new java.awt.Color(153, 51, 255));
        Quina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Quina.setText("Quina");
        Quina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuinaActionPerformed(evt);
            }
        });
        jPanel3.add(Quina);
        Quina.setBounds(20, 170, 190, 50);

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 36)); // NOI18N
        jLabel1.setText("GERADOR DE NÚMEROS");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 20, 400, 80);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(320, 0, 80, 30);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/homerpng.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel3.add(panelImage2);
        panelImage2.setBounds(140, 90, 230, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void megaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_megaActionPerformed
        new MegaSena().setVisible(true);
        
        Model.Gerador.jogo = 6;
        Gerador.megasena();
        num1.setText(String.valueOf(Model.Gerador.vet[0]));
        num2.setText(String.valueOf(Model.Gerador.vet[1]));  
        num3.setText(String.valueOf(Model.Gerador.vet[2]));  
        num4.setText(String.valueOf(Model.Gerador.vet[3]));  
        num5.setText(String.valueOf(Model.Gerador.vet[4]));  
        num6.setText(String.valueOf(Model.Gerador.vet[5]));  
    }//GEN-LAST:event_megaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void QuinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lotomania;
    private javax.swing.JButton Quina;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton mega;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    // End of variables declaration//GEN-END:variables
}
